### ISSUE TITLE
Clear subscriptions programatically

### ISSUE THREAD

**Issue by darrenhaken** [rniemeyer/knockout-postbox#25]
Is it possible to clear subscriptions programatically?

I'm using Jasmine to write unit tests and I've noticed events seem to be firing in unexpected ways across tests. It would be good to clear all subscriptions as a clear up between tests as a guard to this.

I've seen another approach mentioned in an issue where they manually unsubscribe on each topic. However comes with risk as an unsubscribe could be missed, not to mention the overhead of managing each subscription.

**Comment by ffMathy** [comment]
This is incredibly important to me as well. My tests are failing constantly, and I have to arrange them differently for them to magically just work.

It is very critical.

@darrenhaken what is the `H` variable called in the debug version of Postbox?

**Comment by ffMathy** [comment]
Oh, and furthermore, it also breaks my single-page design. If I use Pjax for single-page navigation, I would like to be able to clear my subscriptions when Pjax "navigates" to a new page without changing the URL.

**Comment by ffMathy** [comment]
I created a pull request which adds a unit test for this, and also a method to clear all variables. @rniemeyer could you check it out?

**Comment by rniemeyer** [comment]
@ffMathy - Thanks! I'll take a look when I have a chance.

**Comment by ffMathy** [comment]
@rniemeyer that's awesome! I represent a major corporation (can't mention which, because I can't share details on what technologies we use here), which uses your component.

What I meant to say is that your component makes a difference, and I hope you keep up the good work on maintaining it!

**Comment by rniemeyer** [comment]
There is now a `reset` method in `v0.5.0` that will dispose all subscriptions related to `ko.postbox` functionality.
