### ISSUE TITLE
Using postbox with AMD knockout components

### ISSUE THREAD

**Issue by TLR12** [rniemeyer/knockout-postbox#31]
Dear rniemeyer,

I would like to know how to use postbox with amd knockout components. In your example you manually create the viewmodels and bind directly bind them to the DOM.

However in mine case I register the components using AMD in the following way:

ko.components.register('side-bar', { require: '../../components/settings/side-bar' });

define(['jquery', 'knockout', 'text!./side-bar.html', 'knockout-postbox'], function ($, ko, template) {
      function SideViewModel(params){
             _this.message = ko.observable().subscribeTo('message', function(val){
                       console.log(val);
              });
      }
       return { viewModel: SideViewModel, template: template};
});
From another viewmodel I publish a message as follows: 
 _this.message = ko.observable('test').publishOn('message');

But subscription never fires. Am I doing something wrong?

Regards,

Rabin

**Comment by rniemeyer** [comment]
Hi Rabin-
It does not appear that you are doing anything wrong? Were you able to resolve your issue. The AMD aspect should not cause any difference in behavior. If there is more code or something I can run, then let me know. I would be happy to help you try to resolve your issue. Thanks!
