### ISSUE TITLE
Subscription singular?

### ISSUE THREAD

**Issue by jehendricks** [rniemeyer/knockout-postbox#32]
I'm using Knockout 3.2.0 with Postbox.0.4.2.  I'm fairly new to KO (month and half) but been a developer for many years and have been doing Angular for a year but looking for a simpler lower learning curve approach for my team.  I've decided on KO, Require, RSVP, and Postbox.  Since I'm coming at KO new with Components now a part of KO, I'm taking a very Component-centric approach since that makes templates simple html fragments and allows very nice code organization.  The problem of course is a clean inter-component messaging that is as loosely coupled as possible.  Postbox seemed to be the answer.  So that's my environment.

The first place the Postbox is used within my app is following login.  The login is a KO component for easy reuse across applications and therefore I don't want any tight coupling.  When login is complete, I have the login doing a ko.postbox.publish('logged in', myUserObject);  This then allows my application code to be unaware of the login component while able to be informed when login has been completed and what the authentication details are in the provided myUserObject message payload.

Here's where there is confusion on my part.  I have 3 components and 1 service that subscribe to the 'logged in' message via ko.postbox.subscribe.  Each subscribe has it's own anonymous closure expecting myUserObject as the sole argument.  Only 1 subscriber is informed on the publish.  The informed subscriber is the first one subscribed.  If I comment it out, then the next subscriber get's the message.

Is PostBox suppose to support multiple subscribers?  Is there something I'm suppose to be returning from the subscriber function to indicate continued delivery to other subscribers?

I think PostBox is a fantastic idea, leveraging what is already there to add pubsub but it's currently frustrating me that I can't get it to work the way I need it to.  I really don't want to go to another pubsub solution because that would not leverage what is already available via KO.

Thanks for PostBox and I look forward to hearing what I may be doing wrong.  I can also provide code samples if that would help.

**Comment by jehendricks** [comment]
Oh, as an additional insight, I am using publish and subscribe rather than the observable extensions because 2 of my subscribers are initializers so don't need observables.  The other 2 uses are observables but because the published payload is an object I needed to subscribe via a function to change the observables based on the part of the payload that was appropriate to the observable rather than the observable be for the whole object.

**Comment by rniemeyer** [comment]
@jehendricks - hello! You are expecting the correct behavior. Would love to find a way to help you sort out the issue in your scenario. Maybe you can reproduce based on this fiddle: http://jsfiddle.net/rniemeyer/3f9t5r9L/

**Comment by jehendricks** [comment]
Will see what modifications I can make to see if I can replicate the problem in the fiddle.  Stay tuned.

**Comment by jehendricks** [comment]
modified it somewhat to follow the pattern I'm following.  It doesn't include any of the require stuff nor component stuff and so far I've not been able to replicate the problem.  Going to see how making components changes things.  Just have to see how to do components without require, I jumped right to require based components since that was the direction I felt best supported medium to large apps.  One thing I am wondering, my VM's are prototype based objects as closures using var self=this; internally.  The subscribes are inside the appropriate VM's but are referencing self rather than using the this initializer.  Is that possibly the problem?

**Comment by rniemeyer** [comment]
@jehendricks - the self/this thing, should not cause any issues to the postbox related code. I hope we can get your issue narrowed down.

**Comment by jehendricks** [comment]
I added a component that subscribes along with the other subscribes and everything is going ok.  I did encounter some problems based on my own mis-understandings of KO and that is the component registration etc. need to be defined before the apply bindings.  Is it possible that my use of require is causing something with lazy load?  My custom elements that use the components are in my main template and the require for my main method injects my components so I assume they should be instantiated prior to the applyBindings in the main method itself.  Going to toy with my local code some since I can't replicate in fiddler.

**Comment by rniemeyer** [comment]
Maybe it is possible that your subscriptions are getting created after your login publish?  The `subscribe` API does take a boolean at the end to indicate that you want to initialize with the latest value to aid in issues with the order things are wired up. Not sure when your login message is published.

**Comment by jehendricks** [comment]
So, heres the general structure
index.html
contains header component with subscription

contains login component with form which posts and calls my ajax service the service uses RSVP promise which login component has the processing callback.  This callback contains the publish.  The whole login form will not post until the user enters creds and submits.

the ajax service also has a subscription to register the login token for future ajax calls.

contains timesheet component with subscription which shows the timesheet div as well as fires off a data initialization ajax service call now that the user in authenticated.

contains another component that follows the timesheet pattern but is commented out to simplify the problem.

My timesheet component never shows itself after login unless I comment out the header component subscription and the ajax service subscription.

All the components are injected into my require main.

**Comment by jehendricks** [comment]
I'm going to copy my current app and start reducing to see if I can come up with a least code example.

**Comment by jehendricks** [comment]
leaving work for day, busy evening so probably won't be able to reduce until tomorrow.  I was able to at least dummy the ajax call so I can eliminate the server side.

**Comment by jehendricks** [comment]
So I reduced enough last night to reduce the problem away.  There's something in one of my subscribers that's causing the problem.  This probably means all of this is my code problem and not postBox.  I'm glad for that, I can chase my own problems!  If whatever is happening in my code is negatively impacting postBox I'll let you know in case there's some hardening that can be done, but for now I have to slowly add my code back in until it breaks again.

**Comment by jehendricks** [comment]
Very odd.  I've narrowed it down to the injection of my ajax service.  The ajax service does have a subscription so I can see the possibility of a circular reference.  The problem is my ajax service is suppose to be a singleton.  Will have to dig deeper.

**Comment by jehendricks** [comment]
So now I'm back to needing help.  My subscription was inside my singleton instance instead of outside.  I moved the subscribe to where the singleton get's instantiated which should only happen once.  No dice.  I ran it through debug stepping through the singleton instantiation and proved it only get's executed the one time.  As soon as I comment out the subscribe for the singleton, the problem goes away but of course my singleton no longer get's notified of a successful login.  I can code around it I'm sure but I think using the subscription is still the cleanest way.  I will try and replicate on the fiddler now that I know the exact formula.

**Comment by jehendricks** [comment]
so, now I'm stumped again.  I can't replicate it with a reduced example.  I'm wondering if maybe there is some interactivity with require.js since that's a major part of my app yet not a part of my problem example.

**Comment by rniemeyer** [comment]
Let me know if there is some way that I can help.  Can you tell if your subscription is being made before the message is published?

**Comment by jehendricks** [comment]
Well, I've assumed based on how require.js is suppose to work, but let me check with the debugger.

**Comment by jehendricks** [comment]
Dropped 3 breakpoints, 1 on publish, 1 on subscription, 1 on anon subscription handler.  On page load, subscribe fires.  On successful login publish fires.  anon handler never fires.

I then added 2 additional breakpoints on my ajax service subscription and it's anon handler.  Page load then fires both subscribes.  Successful login fires publish.  anon handler of ajax service fires.  But my timesheet component anon handler still never fires.

The whole time I have another component that subscribes to the login message but does not interact with the ajax service and it gets it's notifications without fail.

I then commented out the subscribe in my ajax service. Page load then fires timesheet subscribe. Successful login fires publish.  timesheet anon handler then fires.

Just very strange.

**Comment by jehendricks** [comment]
You ever have that sinking feeling when you realize you've done something stupid?  Nah, probably not, I'm the stupid one here.  Turns out that since my ajax service is a service object, it's properties are not observable since they are only consumed internally.  The subscribe in the ajax service was copied from the other place the subscribe is working and the property that needed modifying changed.  Only problem is the source of the subscribe is manipulating an observable property and the ajax service object is not observable.  So, a silly pair of parens was my downfall!

Thanks so much for the help!  Keep up the good work with PostBox.  One of these days I'll have to check out some of your additional KO ready libs.

**Comment by rniemeyer** [comment]
No problem. If you run into any issues or see any enhancements for this project, just let me know.
