### ISSUE TITLE
getSubscriptionsCount returns wrong result after unsubscribing 

### ISSUE THREAD

**Issue by rziv** [rniemeyer/knockout-postbox#39]
getSubscriptionsCount (ko subscribable function) returns wrong results after unsubscribing with ko.postbox.unsubscribeFrom.

For example (also available in http://jsfiddle.net/nv4ptr4d/):
var topic='foo';
console.log(ko.postbox.getSubscriptionsCount('foo')); // 0
 ko.postbox.subscribe('foo', function (data) {});   
 console.log(ko.postbox.getSubscriptionsCount('foo'));  // 1
 ko.postbox.unsubscribeFrom('foo');  // 0
 console.log(ko.postbox.getSubscriptionsCount('foo')); // 1 (should be 0)_

And thanks for this great extension.

**Comment by frederikprijck** [comment]
Hi,

ubsubscribeFrom is not used to ubsubscribe from a topic. Instead it is used as opposite of subscribeTo, to unsubscribe from an observable.

Here is a working jsfiddle: http://jsfiddle.net/nv4ptr4d/1/

Basicly, subscribe returns an object (the actual subscription) which has a dispose method.

Please check https://github.com/rniemeyer/knockout-postbox/issues/9 for more information.

**Comment by rniemeyer** [comment]
Thanks @frederikprijck . I was typing a similar answer.

@rziv - you will either want to do:

```
var mySubscription = ko.postbox.subscribe("test", yourHandler);

// then later

mySubscription.dispose();
```

or when using the extensions:

```
var myObservable = ko.observable().subscribeTo("foo");

// then later

myObservable.unsubscribeFrom("foo");

```

Hope that helps!

**Comment by rziv** [comment]
Thanks a lot , the first option works great form me
