### ISSUE TITLE
When publishing a value with a circular reference, a 'cyclic object value' error is thrown

### ISSUE THREAD

**Issue by stijnherreman** [rniemeyer/knockout-postbox#42]
When publishing a value with a circular reference, a 'cyclic object value' error is thrown. This is because of the serialization that happens to fill `topicCache`.

Code to reproduce:

``` js
const foo = {
  id: "foo",
  bar: ko.observable()
}
const bar = {
  id: "bar",
  foo: ko.observable()
}
ko.postbox.subscribe("foo", function() {
  console.log("foo was published");
})

ko.postbox.publish("foo", foo); // console: foo was published

foo.bar(bar);
ko.postbox.publish("foo", foo); // console: foo was published

bar.foo(foo);
ko.postbox.publish("foo", foo); // TypeError: cyclic object value
```

Is this something that can be solved by the library, or is it something I need to solve in my code?

**Comment by stijnherreman** [comment]
I'm currently using this workaround:

```ts
const serializer = ko.postbox.serializer;
ko.postbox.serializer = (object: any) => { return undefined; }
ko.postbox.publish("selectAdministration", this.administration);
ko.postbox.serializer = serializer;
```

I'm not using `subscribeTo(...)`, or `subscribe(...)` with `initializeWithLatestValue` set to `true`, so I don't think I'm breaking anything.

**Comment by frederikprijck** [comment]
As you can see in this fiddle, the exception has nothing to do with knockout.postbox but with serialization.

https://jsfiddle.net/qqqy2q43/

My guess is to fix it in your code as the only way to "fix" (tho I wouldn't call this a bug) this is to replace/remove serialization.

**Comment by stijnherreman** [comment]
> As you can see in this fiddle, the exception has nothing to do with knockout.postbox but with serialization.

I'm aware of the technical details and understand them, but one could argue that the serialization happening here is an implementation detail of knockout-postbox, since I had to dig into the code to understand where the error came from.

**Comment by frederikprijck** [comment]
The best thing to do in order to understand a library is always to dig in the code, so no issue there tbh.

The serialization happening here is totally unrelated from postbox tho, as you can tell by looking at the source code. One could argue that a library, which extends knockout, should be using the same serialization as knockout itself, which postbox is doing.

On the other hand, I wouldn't realy want a library to support your situation for serialization as you have a circular reference which would lead to a never ending (and useless) serialization.

**Comment by stijnherreman** [comment]
> Not that it's my business, but why are you using this circular references ?

We have a UI built with components (hence the use of knockout-postbox, for communication between them), where certain actions can link two viewmodels together and then they sometimes need to access each other's data. There are likely other ways to tackle this without circular references, but this seemed like the easiest and most logical implementation to us.

**Comment by frederikprijck** [comment]
Using circular references will most likely never be the easiest solution in
a language where serializing those objects is not supported.

**Comment by frederikprijck** [comment]
Btw u are using postbox for losely coupling up components yet u bind up view models directly to each other.  Imho not a good idea as u are breaking loosely coupling. 

Not rly related but I just wanted to mention it.

**Comment by frederikprijck** [comment]
Aparantly I can't edit my posts on mobile,  so sorry for the amount of replies. 

Imho if u want a more clean solution then urs I would go for :

- create a ko extension method subscribeWithoutSerialization which allows u for reusing it and even sharing it with the community. 
- create a library (e. g.  Json.parse.circular.js) and override json stringify and parse to handle ur case.  But u can never entirely serialize or deserialize circular references without stopping the circular referencing at some lever.  Ur stack will explode if u try to

**Comment by fqborges** [comment]
I would go for PR with a change like this:
```
    exports.defaultCacheInitializer = function(value) {
        return {
            value: value,
            serialized: exports.serializer(value)
        };
    }
    exports.cacheInitializer = exports.defaultCacheInitializer;
    
    //wrap notifySubscribers passing topic first and caching latest value
    exports.publish = function(topic, value) {
        if (topic) {
            //keep the value and a serialized version for comparison
            exports.topicCache[topic] = exports.cacheInitializer(value);
            exports.notifySubscribers(value, topic);
        }
    };
```

So you can just get rid of all the serialization for initializing and comparing cache values if it does no suit your needs.

**Comment by frederikprijck** [comment]
That might be a bit cleaner then overriding the serializer but the effect is comparable to how @stijnherreman  is overriding the serializer ?

**Comment by fqborges** [comment]
I think that in practice the effect is the same, using the defaults will still throw the serialization error and to avoid it you need to override something. But it will make the library not dependent in serialization anymore, as it is only related to the default cache comparison, and it could be replaced with something else, like timestamps or ids.

**Comment by fqborges** [comment]
Well, something came up now. The serialization concept (`cached.serialized` specifically) could be change to something like a 'hash' or 'memento' or 'identifier'. I mean, something that could be used to compare values like a Object#equals in java. Thinking about it it is used only as a optimization to avoid running serialized(cached.value) over and over.

**Comment by cervengoc** [comment]
Might not be interesting, but when I started to use this library in the past days I simply assigned the `serializer` an identity function like

```
ko.postbox.serializer = function(value) { return value };
```

because I actually don't need the caching and the notification with latest value feature currently.

**Comment by frederikprijck** [comment]
Well eventually you might hit a point where you do need to serialize the object which incluced circular reference, and removing the serializer won't help in that situation. 

If that's the case, you may want to look into Douglas Crockford's cycle.js: https://github.com/douglascrockford/JSON-js
