### ISSUE TITLE
Is possible to send functions instead of data using postbox?

### ISSUE THREAD

**Issue by Tecayehuatl** [rniemeyer/knockout-postbox#44]
I know how to send data from a publish to a subscriber but I would like to send not only data, actually I would like to send a function, is this possible?

**Comment by rniemeyer** [comment]
@Tecayehuatl - Hope you figured out your scenario. While it is not the normal scenario, you should be fine with publishing functions. The only piece that won't work is the logic that compares the latest published value before publishing the same value again.
