### ISSUE TITLE
add a way to clear one ko.postbox.subscribe() ?

### ISSUE THREAD

**Issue by sirber** [rniemeyer/knockout-postbox#45]
sometimes it's easier not to use an observable but a function directly, but there is no way to clear the subscription. if used in a component, the subscriptions will just duplicate each time the component is initialised.

ko.postbox.subscribe() could return an index that would be fed to ko.postbox.reset()

**Comment by rniemeyer** [comment]
@sirber - When you call `subscribe` it returns a subscription object with a `dispose` function. Does it work for you to use it that way?

So, it would look like:

```js
const test = ko.postbox.subscribe("someTopic", someHandlerFunction);

// later when cleaning up
test.dispose();
```

Let me know if that would work for your scenario or we could explore some other ideas.

**Comment by sirber** [comment]
That would be terrific! That would work like a subscribe / dispose in ko.

**Comment by rniemeyer** [comment]
@sirber - yep, that is the way that it already works. Perhaps the docs could be improved a bit on that point. Hope that works for you!

**Comment by sirber** [comment]
you are right! thank you!

![image](https://user-images.githubusercontent.com/3911428/93087198-3b49a280-f666-11ea-8ba0-7172eec6e164.png)

**Comment by rniemeyer** [comment]
@sirber - I updated the README slightly to show that the subscription is returned. Thanks!

**Comment by sirber** [comment]
Thank you!

really nice project, by the way! really useful when using components!
