### ISSUE TITLE
Upcoming next version

### ISSUE THREAD

**Issue by arindam0006in** [rniemeyer/knockout-postbox#48]
Is there any plan to bring the next version of knockout-postbox as it's very old?

**Comment by rniemeyer** [comment]
I guess that I have thought about rewriting it in TypeScript, but have no firm plans at this point. I would be happy to fix bugs, but otherwise it seems to just work the way that it is. Are you having any issues? Thanks!

**Comment by arindam0006in** [comment]
No issues such. As the last published date is around 6 yrs old, due to a few compliance and security issues, we cannot use this version(0.6.0). Could you please publish a new version, with the readme changes you have done, it will be really great?

**Comment by rniemeyer** [comment]
@arindam0006in - ok I published a new build 0.6.1. Hope that helps!

**Comment by arindam0006in** [comment]
Thank you Ryan... It helps a lot.
